FROM fedora
RUN yum install sysbench -y
# RUN yum update -y
RUN mkdir sysb
RUN cp /lib64/libmariadb.so.3 /sysb/
RUN cp /lib64/libpq.so.5 /sysb/
RUN cp /lib64/libluajit-5.1.so.2 /sysb/
RUN cp /lib64/libck.so.0 /sysb/
RUN cp /lib64/libaio.so.1 /sysb/
RUN cp /lib64/libssl.so.1.1 /sysb/
RUN cp /lib64/libcrypto.so.1.1 /sysb/
RUN cp /bin/sysbench /sysb/
CMD ["/bin/bash"]